# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20190529_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='medida',
            field=models.CharField(choices=[('cm3', 'centrimetros cubicos'), ('kg', 'kilogramos'), ('lbs', 'libras')], max_length=5),
        ),
    ]
