# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_auto_20190603_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
