# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20190605_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='medida',
            field=models.CharField(choices=[('m3', 'metros cubicos'), ('kg', 'kilogramos'), ('lbs', 'libras')], max_length=5),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=8),
        ),
    ]
