# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_auto_20190612_0435'),
    ]

    operations = [
        
       
        
    ]
