# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_auto_20190620_1141'),
    ]

    operations = [
       
        
    ]
