# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_auto_20190621_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('entrega', models.CharField(max_length=15)),
                ('recibe', models.CharField(max_length=15)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Chofer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('propietario', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Proveedor'),
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.Vehiculo'),
        ),
    ]
