# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_auto_20190621_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='hora',
        ),
        migrations.AddField(
            model_name='orden',
            name='horae',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='horas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
