# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_auto_20190701_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='horae',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='horas',
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
